### ISSUE TITLE
go-blueprint version string is empty on output instead of it printing the version

### ISSUE THREAD

**Issue by brotherthegrest** [Melkeydev/go-blueprint#124] opened 2023-11-19 18:19 UTC
when go-blueprint version is written the output is just  `Go Blueprint CLI version`
instead of printing the proper output `Go Blueprint CLI version 0.3.0`

**Comment by FMinister** [comment] 2023-11-20 08:02
I would say that this is an error in the [.goreleaser.yml](https://github.com/Melkeydev/go-blueprint/blob/main/.goreleaser.yml) file. There, `github.com/melkeydev/go-blueprint/cmd.GoBlueprintVersion={{.Version}}` should be replaced with `cmd.GoBlueprintVersion={{.Version}}`.

**Comment by limesten** [comment] 2023-11-22 06:56
I believe the problem is that when you install with `go install github.com/melkeydev/go-blueprint@latest`

It will build from the source code rather than using the pre-built binary, and therefore the version variable won't be populated with the ldflag

Working on a fix for this one

**Closed** 2023-12-29 18:00 UTC
